version: "3.3"  

services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:8000"
    environment:
      - DEBUG
      - SECRET_KEY
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
    volumes:
      - .:/code
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 
    
    
#networks: 
#  default:
#    external:
#      name: postgres_default
