version: "3.3"  

services:
  web:
    build: .
      #ports:
      # - "${WEB_PORT}:8000"
    env_file:
      - config.env
    volumes:
      - .:/code
      - /tmp/:/tmp/
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 
    network_mode: "host"
    
    
#networks: 
#  default:
#    external:
#      name: postgres_default
