# Generated by Django 3.1.4 on 2020-12-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
                ('note', models.TextField(blank=True, max_length=511, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257, unique=True)),
                ('note', models.TextField(blank=True, max_length=511, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257, unique=True)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('author', models.CharField(max_length=257, unique=True)),
                ('note', models.TextField(blank=True, max_length=1023, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('name', models.CharField(max_length=257, unique=True)),
                ('ra', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('dec', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('note', models.TextField(blank=True, max_length=511, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects_log.program')),
            ],
        ),
    ]
