# Generated by Django 3.1.4 on 2020-12-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257, unique=True)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('note', models.TextField(blank=True, max_length=1023, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colorfilter',
            name='target',
            field=models.ManyToManyField(to='objects_log.Target'),
        ),
        migrations.AddField(
            model_name='target',
            name='observer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='dec',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='DEC in decimal degree', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='ra',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='RA in decimal hours', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='telescope',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='objects_log.telescope'),
            preserve_default=False,
        ),
    ]
