# Generated by Django 3.1.4 on 2020-12-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0002_auto_20201230_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorfilter',
            name='target',
        ),
        migrations.AddField(
            model_name='target',
            name='colorfilter',
            field=models.ManyToManyField(blank=True, null=True, to='objects_log.ColorFilter'),
        ),
        migrations.AlterField(
            model_name='target',
            name='dec',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='DEC in decimal degree', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='ra',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='RA in decimal hours', max_digits=12, null=True),
        ),
    ]
