# Generated by Django 3.1.4 on 2020-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0004_auto_20201230_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='number_of_frames',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
