# Generated by Django 3.1.4 on 2021-01-03 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0006_colorfilter_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True)),
                ('weight', models.IntegerField(default=0, help_text='For display sorting purposes', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='colorfilter',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='target',
            name='tag',
            field=models.ManyToManyField(to='objects_log.Tag'),
        ),
    ]
