# Generated by Django 3.1.4 on 2021-01-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0007_auto_20210103_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='author',
            field=models.CharField(max_length=257),
        ),
    ]
