# Generated by Django 3.1.4 on 2021-01-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0009_auto_20210103_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='tag',
            field=models.ManyToManyField(blank=True, to='objects_log.Tag'),
        ),
    ]
