# Generated by Django 3.1.4 on 2021-01-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0011_auto_20210104_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='symbol',
            field=models.CharField(blank=True, help_text='Tag HTML symbol. Example symbols can be found here                    https://www.w3schools.com/charsets/ref_utf_symbols.asp', max_length=12, null=True),
        ),
    ]
