# Generated by Django 3.1.4 on 2021-01-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0012_tag_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='symbol',
            field=models.CharField(blank=True, help_text='Tag Hex HTML symbol. Example symbols can be found here                    https://www.w3schools.com/charsets/ref_utf_symbols.asp', max_length=12, null=True),
        ),
    ]
