# Generated by Django 3.1.4 on 2021-01-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0013_auto_20210104_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ('-datetime_start',)},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AlterField(
            model_name='tag',
            name='symbol',
            field=models.CharField(blank=True, default='9873', help_text='Tag HTML symbol. Example symbols can be found here:                    https://www.w3schools.com/charsets/ref_utf_symbols.asp', max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('note', models.TextField(blank=True, max_length=511, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='objects_log.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='night',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='objects_log.night'),
            preserve_default=False,
        ),
    ]
