# Generated by Django 3.1.4 on 2021-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0015_auto_20210125_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='note',
            field=models.TextField(blank=True, default='', max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='total_exposure_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total exposure time in hours', max_digits=7, null=True),
        ),
    ]
