# Generated by Django 3.1.4 on 2021-05-11 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0016_auto_20210218_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorfilter',
            options={'ordering': ('-weight',)},
        ),
        migrations.AlterModelOptions(
            name='night',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-weight',)},
        ),
        migrations.RemoveField(
            model_name='target',
            name='observer',
        ),
        migrations.AddField(
            model_name='target',
            name='observers',
            field=models.ManyToManyField(blank=True, null=True, to='objects_log.Observer'),
        ),
        migrations.AlterField(
            model_name='colorfilter',
            name='weight',
            field=models.IntegerField(default=0, help_text='For display sorting purposes', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(default=0, help_text='For display sorting purposes', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='total_exposure_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total exposure time in seconds', max_digits=7, null=True),
        ),
    ]
