# Generated by Django 3.1.4 on 2021-05-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_log', '0017_auto_20210511_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='ccd_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='ccd_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='exp_note',
            field=models.TextField(blank=True, default='', max_length=257, null=True),
        ),
        migrations.AlterField(
            model_name='observer',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='observers',
            field=models.ManyToManyField(blank=True, to='objects_log.Observer'),
        ),
    ]
